import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import PreFetchLink from '../components/PreFetchLink'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <PreFetchLink className={styles.button} href="/listing/1">Go to Listing!!</PreFetchLink>
        <Link className={styles.button} href="/listingoffssr">Go to Listing SSR OFF!!</Link>
      </main>
    </div>
  )
}
